name: Release

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Deploy Convex
        run: npx convex deploy
        env:
          CONVEX_DEPLOY_KEY: ${{ secrets.CONVEX_DEPLOY_KEY }}
          VITE_CONVEX_URL: ${{ secrets.VITE_CONVEX_URL }}

      - name: Build and publish
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_CONVEX_URL: ${{ secrets.VITE_CONVEX_URL }}
